(ns loam.svg-test
  (:require [clojure.test :refer [deftest is testing]]
            [loam.html :as html]
            [loam.svg :as svg]))

(def safe-dvisvgm-svg
  "<?xml version='1.0' encoding='UTF-8'?>
<!-- generated by dvisvgm -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg'
     xmlns:xlink='http://www.w3.org/1999/xlink' width='10pt' height='5pt'
     viewBox='0 0 10 5'>
<defs><path id='g0' d='m0 0h1v1z'/></defs>
<g fill='currentColor'><use x='0' y='0' xlink:href='#g0'/></g>
</svg>")

(deftest parses-static-dvisvgm-subset-into-hiccup
  (let [hiccup (svg/parse-safe-svg safe-dvisvgm-svg)
        rendered (html/render-canonical-html hiccup)]
    (is (= :svg (first hiccup)))
    (is (re-find #"<path[^>]+id=\"g0\"" rendered))
    (is (re-find #"xlink:href=\"#g0\"" rendered))
    (is (re-find #"fill=\"currentColor\"" rendered))))

(deftest rejects-executable-and-external-svg
  (testing "script elements"
    (is (thrown? clojure.lang.ExceptionInfo
                 (svg/parse-safe-svg
                  "<svg xmlns='http://www.w3.org/2000/svg'><script>alert(1)</script></svg>"))))
  (testing "event attributes"
    (is (thrown? clojure.lang.ExceptionInfo
                 (svg/parse-safe-svg
                  "<svg xmlns='http://www.w3.org/2000/svg' onload='alert(1)'></svg>"))))
  (testing "external hrefs"
    (is (thrown? clojure.lang.ExceptionInfo
                 (svg/parse-safe-svg
                  "<svg xmlns='http://www.w3.org/2000/svg'><use href='https://example.com/a.svg#x'/></svg>")))))
